openapi: "3.1.0"
info:
  title: "individuals_api API"
  description: "individuals_api API"
  version: "1.0.0"
servers:
  - url: "https://individuals_api"
paths:
  /v1/auth/registration:
    post:
      summary: "POST v1/auth/registration"
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
  /v1/auth/login:
    post:
      summary: "POST v1/auth/login"
      operationId: "login"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
  /v1/auth/refresh-token:
    post:
      summary: "POST v1/auth/refresh-token"
      operationId: "refreshToken"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
  /v1/auth/me:
    get:
      summary: "GET v1/auth/me"
      operationId: "getUser"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserResponse"
components:
  schemas:
    RegistrationRequest:
      type: "object"
      properties:
        email:
          type: "string"
          nullable: true
        password:
          type: "string"
          nullable: true
        confirmPassword:
          type: "string"
          nullable: true
    AuthResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
          nullable: true
        expiresIn:
          type: "integer"
          format: "int64"
          nullable: true
        refreshToken:
          type: "string"
          nullable: true
        tokenType:
          type: "string"
          nullable: true
    LoginRequest:
      type: "object"
      properties:
        email:
          type: "string"
          nullable: true
        password:
          type: "string"
          nullable: true
    RefreshTokenRequest:
      type: "object"
      properties:
        refreshToken:
          type: "string"
          nullable: true
    UserResponse:
      type: "object"
      properties:
        id:
          type: "string"
          nullable: true
        email:
          type: "string"
          nullable: true
        roles:
          type: "array"
          nullable: true
          items:
            type: "string"
        createdAt:
          type: "string"
          nullable: true